spring:
  application:
    name: backend-peti9

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/peti9
    username: postgres
    password: 123

    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
